Remove similarity heuristic
ocf/ocflib pull request #216
Opened 2020-07-26 00:16 UTC by bjb568

Fixes #136.

2020-07-26 00:59 UTC, jvperrin commented on tests/account/creation_test.py
> -    @pytest.mark.parametrize('username', [
This and everything below is are not related to the similarity heuristic, so they shouldn't be removed.

2020-07-26 01:01 UTC, jvperrin commented on tests/account/creation_test.py
> -    @pytest.mark.parametrize('username', [
Well ok they reference it, but they're testing some other functionality as well

2020-07-26 01:03 UTC, jvperrin commented on tests/account/creation_test.py
> -    def test_long_names(self, _, __):
This one is still fine to remove though, the permutation issue was only with the similarity heuristic.

2020-07-26 05:25 UTC, bjb568 commented
This PR is pending BoD approval.

2020-09-10 03:55 UTC, bjb568 commented
Approved by BoD.

2020-09-10 04:09 UTC, ja5087 requested changes
otherwise lgtm pending that one test

2020-09-10 04:09 UTC, ja5087 commented on tests/account/creation_test.py
> -    @pytest.mark.parametrize('attrs', [
This unit tests a lot of other functionality which is not a good sign but probably shouldn't be removed.

2020-09-10 04:11 UTC, ja5087 approved these changes
Actually, looking at that test again I am not really sure what it's meant to warn against and it shouldn't block this PR.

2020-09-10 04:12 UTC, merged